import tkinter as tk
root = tk.Tk()
label = tk.Label(text="Oblicz swoje bmi")
label2 = tk.Label(text="Wzrost")
entry1 = tk.Entry()
label3 = tk.Label(text="Waga")
entry2 = tk.Entry()
label2.pack()
entry1.pack()
label3.pack()
entry2.pack()
B = tk.Button(text ="Oblicz")

root.geometry("300x200")
root.title("Oblicz swoje bmi")
root.iconbitmap("")
root.resizable(False,False)
root.mainloop()
